### ISSUE TITLE
onInteractionEnd

### ISSUE THREAD

**Issue by tjbo** [tjallen/react-simple-range#15]
I've been searching for a library like this for half a day. It's very simple and I like that....

However, I am wondering if I contributed if... or have a suggestion or otherwise..

- Do you see the possibility of exposing "onInteractionEnd", so that instead of getting a value after every "onChange" event, we can get one at the end of the interaction?

I don't mind contributing and making a PR here, however just want to know what you guys think of this idea, and the likelihood it could be commited?

**Comment by tjbo** [comment]
onChangeComplete

Is probably a better name...

**Comment by tjallen** [comment]
Hi @tjbo,

This sounds reasonable; feel free to submit a PR with the changes you'd like to see (following the [commit guidelines in the README](https://github.com/tjallen/react-simple-range#contributing)) and I'll check it out.

Cheers.
